// TODO:: Move this into the enum dir

export enum SUCCESS_STATUS_CODE {
  GENERAL_SUCCESS = 'S0000',
  PAYMENT_REQUIRED = 'S0001',
  TWOFA_REQUIRED = 'S0002',
  PAYMENT_OTP_REQUIRED = 'S0004',
  SCANNER_NOT_ACTIVATED = 'ERR0018',
}

export enum VERIFICATION_STATUS {
  NOT_REVIEWED = 'NOT REVIEWED',
  AWAITING_VERIFICATION_FEE_PAYMENT = 'AWAITING PAYMENT',
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  DECLINED = 'DECLINED',
}
